#!/usr/bin/env python3
"""
Glossary builder for 01 Reference knowledge base.

Scans every article body for definition patterns and emits a deduplicated,
source-cited glossary at:
  01 Reference/aggregates/glossary.md

Recognized patterns:
  1. `**Term:** definition...`           bold term + colon
  2. `**Term** — definition...`          bold term + em-dash / en-dash / double-hyphen
  3. `glossary:` frontmatter list (article-opted-in explicit definitions):
       glossary:
         - term: definition...
         - term: definition...

Run:
  python3 "01 Reference/scripts/build_glossary.py"
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

REFERENCE_DIR  = Path(__file__).parent.parent
ARTICLES_DIR   = REFERENCE_DIR / "articles"
AGGREGATES_DIR = REFERENCE_DIR / "aggregates"
OUT            = AGGREGATES_DIR / "glossary.md"

PAT_BOLD_COLON = re.compile(r"\*\*([A-Z][^*]{1,60}?)\*\*\s*:\s*(.+)")
PAT_BOLD_DASH  = re.compile(r"\*\*([A-Z][^*]{1,60}?)\*\*\s*[—–-]{1,2}\s*(.+)")


def parse_frontmatter(text: str) -> tuple[dict, str]:
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    fm = text[4:end]
    body = text[end + 4:].lstrip("\n")
    meta: dict = {}
    current_key: str | None = None
    current_list: list | None = None
    for raw in fm.split("\n"):
        if raw.startswith("  - ") or (current_list is not None and raw.startswith("- ")):
            v = raw.lstrip(" -").strip()
            if current_list is not None:
                current_list.append(v)
            continue
        if ":" not in raw or raw.startswith(" "):
            continue
        key, _, val = raw.partition(":")
        key = key.strip(); val = val.strip()
        if val == "":
            meta[key] = []
            current_list = meta[key]
            current_key = key
        elif val.startswith("[") and val.endswith("]"):
            items = val[1:-1].split(",")
            meta[key] = [i.strip().strip('"').strip("'") for i in items if i.strip()]
            current_list = None
        else:
            meta[key] = val.strip('"').strip("'")
            current_list = None
    return meta, body


def extract_definitions(article_id: str, body: str, meta: dict) -> list[tuple[str, str]]:
    """Return [(term, definition)] tuples found in this article."""
    found: list[tuple[str, str]] = []

    # 1 & 2 — Inline patterns. Walk line by line; only count single-line definitions.
    for line in body.split("\n"):
        line = line.strip()
        if not line.startswith("**"):
            continue
        # Prefer bold-colon match, fall back to bold-dash
        m = PAT_BOLD_COLON.match(line) or PAT_BOLD_DASH.match(line)
        if not m:
            continue
        term = m.group(1).strip()
        definition = m.group(2).strip()
        # Skip if "term" looks like a label (e.g. "Production Base URL")
        # by requiring the definition to be reasonably long
        if len(definition) < 20:
            continue
        # Skip nav-style headings that aren't terms (no spaces) — heuristic
        if term.lower() in {"fix", "symptom", "answer", "note", "tip", "warning"}:
            continue
        found.append((term, definition))

    # 3 — Frontmatter glossary list: items shaped "term: definition"
    for item in meta.get("glossary", []) or []:
        if isinstance(item, str) and ":" in item:
            term, _, defn = item.partition(":")
            term = term.strip(); defn = defn.strip()
            if term and defn:
                found.append((term, defn))

    return found


def build() -> dict[str, list[tuple[str, str]]]:
    """Return {normalized_term: [(article_id, definition)]}"""
    glossary: dict[str, list[tuple[str, str]]] = defaultdict(list)
    display_name: dict[str, str] = {}

    for path in sorted(ARTICLES_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(text)
        aid = meta.get("id", path.stem)
        for term, defn in extract_definitions(aid, body, meta):
            key = term.lower()
            display_name.setdefault(key, term)
            glossary[key].append((aid, defn))

    # Rebuild with display_name as key
    return {display_name[k]: v for k, v in glossary.items()}


def write_glossary(glossary: dict[str, list[tuple[str, str]]]) -> None:
    AGGREGATES_DIR.mkdir(exist_ok=True)
    lines = [
        "# Glossary",
        "",
        f"_Auto-generated by `build_glossary.py`. {len(glossary)} terms from "
        f"{len({a for entries in glossary.values() for a, _ in entries})} articles. Do not edit._",
        "",
    ]

    # Group by first letter
    by_letter: dict[str, list[str]] = defaultdict(list)
    for term in glossary:
        first = term[0].upper() if term else "#"
        by_letter[first].append(term)

    for letter in sorted(by_letter):
        lines.append(f"## {letter}")
        lines.append("")
        for term in sorted(by_letter[letter], key=lambda s: s.lower()):
            lines.append(f"### {term}")
            for aid, defn in glossary[term]:
                lines.append(f"From `{aid}`:")
                lines.append(f"> {defn}")
                lines.append("")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"glossary.md: {len(glossary)} terms")


if __name__ == "__main__":
    if not ARTICLES_DIR.exists():
        print(f"ERROR: articles directory not found at {ARTICLES_DIR}", file=sys.stderr)
        sys.exit(1)
    glossary = build()
    if not glossary:
        # Still write an empty file so the aggregate exists
        AGGREGATES_DIR.mkdir(exist_ok=True)
        OUT.write_text(
            "# Glossary\n\n_Auto-generated by `build_glossary.py`. No definition patterns found in articles._\n",
            encoding="utf-8",
        )
        print("glossary.md: 0 terms (no definition patterns detected)")
        sys.exit(0)
    write_glossary(glossary)
    print("Done.")
